### PR TITLE
Accesibility

### PR DESCRIPTION
**Pull request by baezluise**

### CODE REVIEW

**Comment by JuanDBta** [comment]
When we ran the Accessibility Evaluation Tools we got the following report:

25 Errors:
  10 X Missing alternative text
  11 X Linked image missing
  3 X Empty form label
  1 X Empty link

23 Contrast Errors:
  23 X Very low contrast

1 Feature
  1 X Language

30 Structural Elements
   2 X Heading level 1
  11 X Heading Level 2
  14 X Unordered list
  1 X Header
 1 X Navigation
 1 X Footer

Now, we are fixing such errors and you can see in the next comments the lines of code we have to change,

**Comment by JuanDBta** [comment]
In the section Errors - 10 X Missing alternative text.  We add the alt attribute alt="" to provide a clear description of the element.  For example in this code line:
https://github.com/baezluise/portfolio-project/blob/dc9cb91e91c3bf36c58c086b2a1d3f46416ca286/index.html#L13

**Comment by JuanDBta** [comment]
In section 11 X Linked image missing. 
We added alt attribute to social media icons.
https://github.com/baezluise/portfolio-project/blob/dc9cb91e91c3bf36c58c086b2a1d3f46416ca286/index.html#L34-L38

**Comment by JuanDBta** [comment]
In section 3 X Empty form label.
We  added text to the tag
https://github.com/baezluise/portfolio-project/blob/dc9cb91e91c3bf36c58c086b2a1d3f46416ca286/index.html#L166

**Comment by JuanDBta** [comment]
In section 1 X Empty link.
  We changed the <a> tag, and is now embedding the  tag

  https://github.com/baezluise/portfolio-  project/blob/dc9cb91e91c3bf36c58c086b2a1d3f46416ca286/index.html#L41

**Comment by JuanDBta** [comment]
In Section, 23 Contrast Errors:  23 X Very low contrast.

We changed the background color to #1a5b40 in order to have better lightness. 

https://github.com/baezluise/portfolio-project/blob/dc9cb91e91c3bf36c58c086b2a1d3f46416ca286/styles.css#L160-L172

**Comment by baezluise** [comment]
## Accesibility Report 🖨️

# Page titles

no issues

# Image text alternatives

In section 11 X Linked image missing.
We added alt attribute to social media icons. [see code here](https://github.com/baezluise/portfolio-project/blob/dc9cb91e91c3bf36c58c086b2a1d3f46416ca286/index.html#L34-L38)

# Text headings

no issues found

# Color contrast

In Section, 23 Contrast Errors: 23 X Very low contrast.
We changed the background color to #1a5b40 in order to have better lightness. [see code here](https://github.com/baezluise/portfolio-project/blob/dc9cb91e91c3bf36c58c086b2a1d3f46416ca286/styles.css#L160-L172)

# Resize

no issues found

# Interaction

No issues found

# Moving content

no issues found

# Multimedia

no issues found

# The basic structure of the page

no issues found

**Review by Trast00 — APPROVED** [review]
# Approved 🟢
Hi @baezluise , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
allfather-approves-approved

## Highlights
- Project look awsome 🍏 🌷 
- Code is clean and well organized 🧼 💯 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@Trast00) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
